<a href="https://colab.research.google.com/github/Mular56/Machine_learning/blob/main/%D0%9C%D1%83%D0%BB%D1%8F%D1%80_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Муляр Вікторія
Варіант 20

In [1]:
# Завдання 1
# Створіть одновимірний масив (вектор) з сумами кожного числа та його
# попереднього, починаючи з 1, та виведіть його значення.

import numpy as np

n = 10
arr = np.arange(1, n + 1)
result = np.zeros(n, dtype=int)

for i in range(n):
    if i == 0:
        result[i] = arr[i]
    else:
        result[i] = arr[i] + arr[i - 1]

print(result)


[ 1  3  5  7  9 11 13 15 17 19]


In [2]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
# випадкових дійсних чисел від 1 до 10.

import numpy as np

rows, cols = 3, 3
matrix = np.random.uniform(1, 10, size=(rows, cols))

print(matrix)


[[2.56043802 1.81634342 5.95976177]
 [9.69797122 4.69066527 9.89048635]
 [7.25672534 3.25715327 9.53015224]]


In [4]:
# Завдання 3
# Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
# 1 до 100 та виведіть мін значення

import numpy as np

rows, cols = 3, 3
matrix = np.random.randint(1, 101, size=(rows, cols))
min_value = np.min(matrix)

print("Матриця:")
print(matrix)
print("Мінімальне значення:", min_value)


Матриця:
[[ 9 83 37]
 [ 8 70 47]
 [54 67 66]]
Мінімальне значення: 8


In [5]:
# Завдання 4
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.

import numpy as np

matrix = np.random.uniform(0, 1, size=(4, 4))
count = np.sum(matrix > 0.5)

print("Матриця:")
print(matrix)
print("Кількість елементів, що більше 0.5:", count)


Матриця:
[[0.14677948 0.29427223 0.421005   0.86380585]
 [0.78499895 0.67860303 0.15544116 0.62540184]
 [0.36699419 0.68321033 0.59373711 0.42369064]
 [0.50239989 0.71174079 0.78755388 0.29369677]]
Кількість елементів, що більше 0.5: 9


In [6]:
# Завдання 5
# Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими
# числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання
# та множення.

import numpy as np

array1 = np.random.randint(-10, 11, size=4)
array2 = np.random.randint(-10, 11, size=4)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Масив 1:")
print(array1)
print("Масив 2:")
print(array2)
print("Додавання:")
print(addition)
print("Віднімання:")
print(subtraction)
print("Множення:")
print(multiplication)


Масив 1:
[10  9 -6  8]
Масив 2:
[  0  -1 -10   6]
Додавання:
[ 10   8 -16  14]
Віднімання:
[10 10  4  2]
Множення:
[ 0 -9 60 48]


In [7]:
# Завдання 6
# Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 20 та
# знайдіть їх добуток.

import numpy as np

matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[11 16 12]
 [ 1  4  6]
 [ 8  3  2]]
Матриця 2:
[[ 8  2 16]
 [11 10 14]
 [ 7 14  2]]
Добуток матриць:
[[348 350 424]
 [ 94 126  84]
 [111  74 174]]


In [8]:
# Завдання 7
# Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 4 та перемножте їх між собою.

import numpy as np

matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 3))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[1 2 1]
 [4 4 3]]
Матриця 2:
[[3 4 1]
 [1 4 4]
 [4 3 3]]
Добуток матриць:
[[ 9 15 12]
 [28 41 29]]


In [9]:
# Завдання 8
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 1 до 7 та знайдіть її обернену матрицю.

import numpy as np

matrix = np.random.randint(1, 8, size=(3, 3))

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Матриця:")
    print(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не є оберненою (можливо, її детермінант дорівнює нулю).")


Матриця:
[[1 5 3]
 [1 6 7]
 [7 3 3]]
Обернена матриця:
[[-0.02727273 -0.05454545  0.15454545]
 [ 0.41818182 -0.16363636 -0.03636364]
 [-0.35454545  0.29090909  0.00909091]]


In [10]:
# Завдання 9
# Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні
# від 0 до 1 та транспонуйте її.

import numpy as np

matrix = np.random.randint(0, 2, size=(4, 4))
transposed_matrix = np.transpose(matrix)

print("Матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Матриця:
[[1 1 0 0]
 [1 1 1 1]
 [0 0 1 0]
 [1 0 0 0]]
Транспонована матриця:
[[1 1 0 1]
 [1 1 0 0]
 [0 1 1 0]
 [0 1 0 0]]


In [11]:
# Завдання 10
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
# від 0 до 1, і знайдіть добуток матриці на вектор

import numpy as np

matrix = np.random.uniform(0, 1, size=(3, 4))
vector = np.random.uniform(0, 1, size=(4, 1))

product = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці на вектор:")
print(product)


Матриця:
[[0.20865856 0.84838036 0.39589847 0.5550927 ]
 [0.55169381 0.13835769 0.15385238 0.52132836]
 [0.32612889 0.04854514 0.63985967 0.46546789]]
Вектор:
[[0.60292666]
 [0.71714268]
 [0.53189329]
 [0.78211308]]
Добуток матриці на вектор:
[[1.37893658]
 [0.92142389]
 [0.93583119]]


In [14]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
# від 0 до 1, і знайдіть добуток матриці на вектор

import numpy as np

matrix = np.random.uniform(0, 1, size=(2, 3))
vector = np.random.uniform(0, 1, size=(3, 1))

product = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці на вектор:")
print(product)


Матриця:
[[0.20834135 0.50535003 0.53846732]
 [0.20760692 0.12500758 0.34317715]]
Вектор:
[[0.35899232]
 [0.74599142]
 [0.62880905]]
Добуток матриці на вектор:
[[0.79037285]
 [0.38357677]]


In [15]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 5 та знайдіть добуток елементів діагоналі другої матриці.

import numpy as np

matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

diagonal_elements = np.diag(matrix2)
product_of_diagonal = np.prod(diagonal_elements)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток елементів діагоналі другої матриці:")
print(product_of_diagonal)


Матриця 1:
[[1 5 1]
 [4 1 3]
 [4 1 4]]
Матриця 2:
[[2 5 4]
 [5 5 3]
 [2 5 5]]
Добуток елементів діагоналі другої матриці:
50


In [16]:
# Завдання 13
# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 5 та знайдіть різницю їх елементів.

import numpy as np

matrix1 = np.random.randint(1, 6, size=(4, 4))
matrix2 = np.random.randint(1, 6, size=(4, 4))

difference = matrix1 - matrix2

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Різниця матриць:")
print(difference)


Матриця 1:
[[3 5 3 1]
 [1 5 1 2]
 [2 3 3 5]
 [2 5 1 3]]
Матриця 2:
[[5 2 3 2]
 [3 4 3 3]
 [1 3 3 1]
 [5 1 3 4]]
Різниця матриць:
[[-2  3  0 -1]
 [-2  1 -2 -1]
 [ 1  0  0  4]
 [-3  4 -2 -1]]


In [18]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 1 до 10 та знайдіть найменший елемент матриці.

import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))
min_element = np.min(matrix)

print("Матриця:")
print(matrix)
print("Найменший елемент матриці:")
print(min_element)


Матриця:
[[ 6  1 10]
 [ 4  2  2]
 [ 8  9  5]]
Найменший елемент матриці:
1


In [19]:
# Завдання 15
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить кількість ненульових
# елементів в кожному рядку матриці.

import numpy as np

matrix = np.random.uniform(-2, 2, size=(3, 3))
non_zero_counts = np.sum(matrix != 0, axis=1)

print("Матриця:")
print(matrix)
print("Кількість ненульових елементів в кожному рядку:")
print(non_zero_counts)


Матриця:
[[ 1.98963527  1.84599625  1.35182506]
 [ 0.42056396  0.39977655 -0.58143856]
 [-1.78629286  0.96836641 -1.61241411]]
Кількість ненульових елементів в кожному рядку:
[3 3 3]


In [ ]:
"""
Висновок:
У ході виконання лабораторної роботи було розглянуто використання бібліотеки NumPy
для роботи з масивами і матрицями. Було створено різні типи масивів, заповнені випадковими
числами, виконано операції додавання, віднімання, множення, транспонування, знаходження
оберненої матриці, добутку матриць та інші математичні операції. Використання NumPy дозволяє
ефективно працювати з великими наборами даних і виконувати обчислення з високою продуктивністю.
Завдання продемонстрували основні можливості бібліотеки для маніпуляцій з масивами та матрицями.
"""
